### ISSUE TITLE
Can't start app, error 502 and unable to open database

### ISSUE THREAD

**Issue by stilobique** [YunoHost-Apps/jellyfin_ynh#112]
### Describe the bug
With a new machine, and a fresh installation with **Debian 11**, no issue to install Jellyfin, but no way to execute the program.
I see this error with some pull request are solved (#87).

### Logs
```text
juil. 30 15:44:46 systemd[1]: Started Jellyfin Media Server.
juil. 30 15:44:48 jellyfin[3703]: [15:44:48] [ERR] [1] Jellyfin.Server.Migrations.MigrationRunner: Could not apply migration 'MigrateActivityLogDatabase'
juil. 30 15:44:48 jellyfin[3703]: CannotOpen: SQLitePCL.pretty.SQLiteException: unable to open database file
juil. 30 15:44:48 jellyfin[3703]:    at SQLitePCL.pretty.SQLiteException.Throw(Int32 rc, Int32 extended, String msg)
juil. 30 15:44:48 jellyfin[3703]:    at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3 db, Int32 rc)
juil. 30 15:44:48 jellyfin[3703]:    at SQLitePCL.pretty.SQLiteDatabaseConnectionBuilder.Build()
juil. 30 15:44:48 jellyfin[3703]:    at Jellyfin.Server.Migrations.Routines.MigrateActivityLogDb.Perform()
juil. 30 15:44:48 jellyfin[3703]:    at Jellyfin.Server.Migrations.MigrationRunner.PerformMigrations(IMigrationRoutine[] migrations, MigrationOptions migrationOptions, Action`1 saveConfiguration, ILogger logger)
juil. 30 15:44:48 jellyfin[3703]: [15:44:48] [FTL] [1] Main: Error while starting server.
juil. 30 15:44:48 jellyfin[3703]: CannotOpen: SQLitePCL.pretty.SQLiteException: unable to open database file
juil. 30 15:44:48 jellyfin[3703]:    at SQLitePCL.pretty.SQLiteException.Throw(Int32 rc, Int32 extended, String msg)
juil. 30 15:44:48 jellyfin[3703]:    at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3 db, Int32 rc)
juil. 30 15:44:48 jellyfin[3703]:    at SQLitePCL.pretty.SQLiteDatabaseConnectionBuilder.Build()
juil. 30 15:44:48 jellyfin[3703]:    at Jellyfin.Server.Migrations.Routines.MigrateActivityLogDb.Perform()
juil. 30 15:44:48 jellyfin[3703]:    at Jellyfin.Server.Migrations.MigrationRunner.PerformMigrations(IMigrationRoutine[] migrations, MigrationOptions migrationOptions, Action`1 saveConfiguration, ILogger logger)
juil. 30 15:44:48 jellyfin[3703]:    at Jellyfin.Server.Migrations.MigrationRunner.Run(CoreAppHost host, ILoggerFactory loggerFactory)
juil. 30 15:44:48 jellyfin[3703]:    at Jellyfin.Server.Program.StartApp(StartupOptions options)
juil. 30 15:44:48 systemd[1]: jellyfin.service: Succeeded.
juil. 30 15:44:48 systemd[1]: jellyfin.service: Consumed 2.269s CPU time.
```

I have access in SSH and check some feedback find with the [yunohost forum](https://forum.yunohost.org/t/jellyfin-502-bad-gateway/16100/3).

```shell
sudo ls -la /etc/jellyfin
drwxr-x---   2 jellyfin jellyfin  4096 Jul 26 01:16 .
drwxr-xr-x 150 root     root     12288 Jul 30 14:10 ..
-rw-r--r--   1 jellyfin jellyfin  1362 Jul 26 01:16 logging.default.json
-rw-r-----   1 jellyfin jellyfin  1356 Jul 26 01:16 logging.json
-rw-r--r--   1 jellyfin jellyfin   700 Jul 26 01:16 migrations.xml
-rw-r-----   1 jellyfin jellyfin  1390 Jul 26 01:16 network.xml
-rw-r-----   1 jellyfin jellyfin  5656 Jul 26 01:16 system.xml
```

```shell
sudo ls -la /var/lib/jellyfin
drwxr-x---   2 jellyfin jellyfin  4096 Jul 26 01:16 .
drwxr-xr-x 150 root     root     12288 Jul 30 14:10 ..
drwxr-x---  5 jellyfin jellyfin 4096 Jul 26 01:16 .
drwxr-xr-x 77 root     root     4096 Jul 26 01:35 ..
drwxr-xr-x  2 jellyfin jellyfin 4096 Jul 30 15:54 data
drwxr-xr-x  2 jellyfin jellyfin 4096 Jul 26 01:16 metadata
drwxrwxrwx  4 jellyfin jellyfin 4096 Jul 26 01:16 plugins
```

**Comment by stilobique** [comment]
Hello,
after small testing day, on a fresh install I replace the `migration.xml` with a new file (get from a Arch Linux jellyfin installed. And everything are good.

[migrations.zip](https://github.com/YunoHost-Apps/jellyfin_ynh/files/9997474/migrations.zip)

**Comment by tituspijean** [comment]
Closing, since it has been more than a year.
Sorry for the inconvenience, feel free to reopen if needed.a
