### ISSUE TITLE
Jellyfin YNH 1.10 server won't start after install on YunoHost 12 because of FFMPEG

### ISSUE THREAD

**Issue by GGGQO** [YunoHost-Apps/jellyfin_ynh#180]
Hi,
I recently deinstalled Jellyfin 10.9 from my YunoHost 11, updated Yunohost to version 12, and then reinstalled Jellyfin 10.10.
Jellyfin 10.10 installation went smoothly, no problem occured.
But it appears that I am unable to log into the Jellyfin server.
Choosing the server on the jellyfin landing page shows a message like "unable to connect to server, verify that it is operational and retry"
"Nous sommes dans l'impossibilité de nous connecter au serveur sélectionné. Veuillez vérifier qu'il est opérationnel et réessayez."
Checking the log gives more info, I have a FATAL error preventing the server to startup correctly, pointing of FFMPEG :

Useful errors : 
`[2024-11-17 14:46:52.188 +01:00] [ERR] Error validating encoder
System.ComponentModel.Win32Exception (2): An error occurred trying to start process ‘/usr/lib/jellyfin-ffmpeg/ffmpeg’ with working directory ‘/var/lib/jellyfin’. No such file or directory
at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String argv, String envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32 groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
at MediaBrowser.MediaEncoding.Encoder.EncoderValidator.GetProcessOutput(String path, String arguments, Boolean readStdErr, String testKey)
at MediaBrowser.MediaEncoding.Encoder.EncoderValidator.ValidateVersion()
[2024-11-17 14:46:52.194 +01:00] [ERR] FFmpeg: Failed version check: “/usr/lib/jellyfin-ffmpeg/ffmpeg”
[2024-11-17 14:46:52.194 +01:00] [ERR] FFmpeg: Path set by “command line or environment variable” is invalid
[2024-11-17 14:46:52.194 +01:00] [FTL] Error while starting server
MediaBrowser.Common.FfmpegException: Failed to find valid ffmpeg
at Emby.Server.Implementations.ApplicationHost.RunStartupTasksAsync()
at Jellyfin.Server.Program.StartServer(IServerApplicationPaths appPaths, StartupOptions options, IConfiguration startupConfig)`

Full log here : https://paste.yunohost.org/oqumiwodeq

I have seen mentions of FFMPEG changes in the recent commits for 10.10 version, maybe there is something more to address on this.
Thanks

**Comment by tituspijean** [comment]
What are the outputs of the following commands?

```
which ffmpeg
/usr/lib/jellyfin-ffmpeg/ffmpeg
```

Can you share your last Jellyfin upgrade log?

**Comment by GGGQO** [comment]
Hi,

`root@noself:~# which ffmpeg
/usr/bin/ffmpeg`

I did not do an update, I removed 1.09 and then installed 1.10, does that change anything ?
can you tell me where that log is located ?

**Comment by tituspijean** [comment]
Sorry for the long delay, are you still experiencing this issue with v10.10.7?

**Comment by GGGQO** [comment]
Hi,
No worries, I used Navidrome as a backup during the time it was not working ...
But I have been using version 10.10.5~ynh2 and the issue was fixed with it as I could use Jellyfin without any problem.
I just updated to 10.10.7 and it is working also.
Thanks
