### ISSUE TITLE
Installation issues (10.7.5)

### ISSUE THREAD

**Issue by Salamandar** [YunoHost-Apps/jellyfin_ynh#72]
As I said on the other issue, I'm reinstalling Jellyfin from scratch.
And…
```
Info: [##########+.........] > Configuring the settings...
Info: The service jellyfin has correctly executed the action restart.
Warning: sed: can't read /etc/jellyfin/network.xml: No such file or directory
Error: Unable to install jellyfin: An error occurred inside the app installation script
Info: The operation 'Install the 'jellyfin' app' could not be completed. Please share the full log of this operation using the command 'yunohost log share 20210514-075237-app_install-jellyfin' to get help
```

**Comment by Salamandar** [comment]
After some debugging I found 2 major issues :

### No write permission on data directory /var/lib/jellyfin

```
admin@salamandar ~/jellyfin_ynh ❯❯❯ sudo journalctl -xeu jellyfin                                                                                                                                                                  ✘ 130 
-- 
-- The job identifier is 29148 and the job result is done.
May 14 09:53:37 salamandar.fr systemd[1]: Started Jellyfin Media Server.
-- Subject: A start job for unit jellyfin.service has finished successfully
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- A start job for unit jellyfin.service has finished successfully.
-- 
-- The job identifier is 29148.
May 14 09:53:38 salamandar.fr jellyfin[11188]: Unhandled Exception
May 14 09:53:38 salamandar.fr jellyfin[11188]: System.UnauthorizedAccessException: Access to the path '/var/lib/jellyfin' is denied.
May 14 09:53:38 salamandar.fr jellyfin[11188]:  ---> System.IO.IOException: Permission denied
May 14 09:53:38 salamandar.fr jellyfin[11188]:    --- End of inner exception stack trace ---
May 14 09:53:38 salamandar.fr jellyfin[11188]:    at System.IO.FileSystem.CreateDirectory(String fullPath)
May 14 09:53:38 salamandar.fr jellyfin[11188]:    at System.IO.Directory.CreateDirectory(String path)
May 14 09:53:38 salamandar.fr jellyfin[11188]:    at Jellyfin.Server.Program.CreateApplicationPaths(StartupOptions options)
May 14 09:53:38 salamandar.fr jellyfin[11188]:    at Jellyfin.Server.Program.StartApp(StartupOptions options)
May 14 09:53:38 salamandar.fr jellyfin[11188]:    at Jellyfin.Server.Program.<Main>(String[] args)
May 14 09:53:38 salamandar.fr jellyfin[11188]: Unhandled exception. System.UnauthorizedAccessException: Access to the path '/var/lib/jellyfin' is denied.
May 14 09:53:38 salamandar.fr jellyfin[11188]:  ---> System.IO.IOException: Permission denied
May 14 09:53:38 salamandar.fr jellyfin[11188]:    --- End of inner exception stack trace ---
May 14 09:53:38 salamandar.fr jellyfin[11188]:    at System.IO.FileSystem.CreateDirectory(String fullPath)
May 14 09:53:38 salamandar.fr jellyfin[11188]:    at System.IO.Directory.CreateDirectory(String path)
May 14 09:53:38 salamandar.fr jellyfin[11188]:    at Jellyfin.Server.Program.CreateApplicationPaths(StartupOptions options)
May 14 09:53:38 salamandar.fr jellyfin[11188]:    at Jellyfin.Server.Program.StartApp(StartupOptions options)
May 14 09:53:38 salamandar.fr jellyfin[11188]:    at Jellyfin.Server.Program.<Main>(String[] args)
May 14 09:53:38 salamandar.fr systemd[1]: jellyfin.service: Main process exited, code=killed, status=6/ABRT
```

I fixed the issue with this patch (not sure the mkdir is necessary, IDK when the dir is created) : 
```
diff --git a/scripts/install b/scripts/install
index 556ef08..13a95fa 100644
--- a/scripts/install
+++ b/scripts/install
@@ -88,6 +88,10 @@ ynh_exec_warn_less apt-get -f install $tempdir/jellyfin-ffmpeg.deb -y
 ynh_exec_warn_less apt-get -f install $tempdir/jellyfin-server.deb -y
 ynh_exec_warn_less apt-get -f install $tempdir/jellyfin-web.deb -y
 
+mkdir -p $final_path
+chown -R $app: $final_path
+
 #=================================================
 # NGINX CONFIGURATION
 #=================================================
```

**Comment by Salamandar** [comment]
I also had to enable ipv6 in network.xml and system.xml, and remove the default server visible on the login page. I re-added it with https://<domain>/<path>. Now it all works fine.

**Comment by tituspijean** [comment]
Hi! I could replicate none of the issues in your first two posts.
Can you provide the full installation log, and your YunoHost version?

**Comment by Salamandar** [comment]
> config properties in network.xml supercedes system.xml

That's weird, but well.

>  I re-added it with https://<domain>/<path>

That may have been an issue with my browser cache. The login page had saved the original server, so you may ignore this issue I think.

**Comment by lentemoore** [comment]
I have also tried reinstalling Jellyfin and come across the same error message, unsure if it's the same problem. Full logs here: https://paste.yunohost.org/raw/zifevabesa

**Comment by lentemoore** [comment]
My Issue with install is fixed in the testing branch. Interesting enough, it is now only accessible via ip address in the local network. Trying to access via domain gets me stuck on the select server screen with a connection error when I choose my server. Well, at least install works :)

**Comment by Salamandar** [comment]
> My Issue with install is fixed in the testing branch. Interesting enough, it is now only accessible via ip address in the local network. Trying to access via domain gets me stuck on the select server screen with a connection error when I choose my server. Well, at least install works :)


Had the same issue, resolved by removing the server from the list and re-uddeng et manially by hostname.

Maybe you're missing something on either dns records or router port redirection ?

**Comment by Salamandar** [comment]
Should be fixed.
